//defines.h
#ifndef __DEFINES_H__
#define __DEFINES_H__

#define SETBIT(WORD,BITPOS) (WORD |=1<<BITPOS)
#define SSETBIT(WORD,BITPOS) (WORD =1<<BITPOS)
#define CLRBIT(WORD,BITPOS) (WORD &=~(1<<BITPOS))
#define SCLRBIT(WORD,BITPOS) (SSETBIT(WORD,BITPOS)) //(WORD =1<<BITPOS)
#define CPLBIT(WORD,BITPOS) (WORD ^=1<<BITPOS)
#define READBIT(WORD,BITPOS) ((WORD>>BITPOS)&1)
#define READNIBBLE(WORD,BNITPOS) ((WORD>>BITPOS)&15)
#define READBYTE(WORD,BITPOS) ((WORD>>BITTPOS)&255)
#define WRITEBIT(WORD,BITPOS,BIT) (WORD =(WORD &(~(1<<BITPOS)) | (BIT<<BITPOS))
#define WRITENIBBLE(WORD,SBITPOS,NIBBLE) (WORD =(WORD &(~(15<<SBITPOS)) | (NIBBLE<<SBITPOS))
#define WRITEBYTE(WORD,SBITPOS,BYTE) (WORD =(WORD &(~(255<<SBITPOS))) | (BYTE<<SBITPOS))
//same words(same register)
#define READWRITEBIT(WORD,SBIT,DBIT) (WORD =(WORD &(~(1<<DBIT)) | ((WORD>>SBIT)&1)<<DBIT)
//different words(different variables)
#define READWRITEBIT2(DWORD,DBIT,SWORD,SBIT) ((DWORD =(DWORD &(~(1<<DBIT)))) | (((SWORD>>SBIT)&1)<<DBIT))

#endif

